name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: |
          npm install
          npm run lint
          npm run compile
          npm run test
          npm run dev
